/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import {
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
  precacheAndRoute,
} from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { NetworkFirst, NetworkOnly } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { API_CACHE_NAME, apiCacheKey } from './sw-cache-key'

declare const self: ServiceWorkerGlobalScope

// `registerType: 'autoUpdate'` only downloads the new worker; with
// injectManifest nothing calls skipWaiting on our behalf. Without these two
// lines a new build sits in "waiting" for as long as any tab stays open, and
// the previous worker keeps serving the previous app shell — which is how a
// deployed auth fix can be live on the server and still absent in the browser.
self.skipWaiting()
clientsClaim()

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// skipWaiting means an old shell can be swapped out mid-session, so drop the
// precaches it belonged to rather than leaving them to be served later.
cleanupOutdatedCaches()

// Credentials and session state must never be served from a cache: a stale
// /api/me would resurrect the previous user's identity. Registered first so it
// wins over the general /api/ route below.
registerRoute(
  ({ url }) =>
    url.pathname.startsWith('/api/auth/') || url.pathname === '/api/me',
  new NetworkOnly(),
)

// Runtime cache for API calls, partitioned per account so a device shared by
// two users never serves one's data to the other.
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: API_CACHE_NAME,
    plugins: [
      {
        cacheKeyWillBeUsed: async ({ request }) => apiCacheKey(request),
      },
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 300,
      }),
    ],
  }),
)

// Every client-side route has to resolve to the same app shell. Precaching
// alone does not do that: workbox maps a bare `/` onto the precached
// index.html, but `/settings` matches nothing and falls through to the network,
// so the two paths could boot different builds of the app at the same time.
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('index.html'), {
    denylist: [/^\/api\//, /^\/uploads\//],
  }),
)

// Drop cached API responses when the page signs out, so nothing survives for
// the next account on this device.
self.addEventListener('message', (event) => {
  if (event.data?.type === 'CLEAR_API_CACHE') {
    event.waitUntil(caches.delete(API_CACHE_NAME))
  }
})

// Push notification handler
self.addEventListener('push', (event) => {
  if (!event.data) return

  let payload: { title?: string; body?: string; url?: string }
  try {
    payload = event.data.json()
  } catch {
    payload = { title: 'Zaindari', body: event.data.text() }
  }

  const title = payload.title || 'Zaindari'
  const options: NotificationOptions = {
    body: payload.body || '',
    icon: '/favicon.ico',
    badge: '/favicon.ico',
    data: { url: payload.url || '/' },
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

// Notification click handler
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const url = (event.notification.data?.url as string) || '/'

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clients) => {
        // Focus an existing window if available
        for (const client of clients) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.navigate(url)
            return client.focus()
          }
        }
        // Otherwise open a new window
        return self.clients.openWindow(url)
      }),
  )
})
