import { TaskType } from '@prisma/client';
import { BadRequestException } from '@nestjs/common';
import { apiError, ERROR_CODES } from '../common/errors/api-error.js';

/**
 * The on-disk shape of an export, and the parser that decides what an imported
 * file is allowed to contain.
 *
 * A bundle is a zip of three things:
 *
 *   manifest.json      what this file is and who made it
 *   data.json          plants, their schedules, and the user's own settings
 *   images/<id>.webp   one entry per photo, named by the id used in data.json
 *
 * Everything here is untrusted on the way in. A bundle is a file a user can
 * hand-edit, mail to themselves, or hand to someone else, so the parser below
 * is a validation boundary, not a cast: it re-derives every value rather than
 * trusting the JSON's shape, and anything it does not recognise is dropped
 * instead of being passed through to Prisma.
 *
 * **Tasks are deliberately not in the format.** A task is a live scheduling
 * fact -- one pending row per (plant, taskType), a `dueAt` that the cron tick
 * reasons about, and a per-recipient notification latch that only makes sense
 * on the instance that wrote it. Carrying that across instances would either
 * resurrect a backlog of overdue work or fire a burst of pushes on the next
 * tick. An imported plant instead arrives with no task history at all, which
 * `SchedulerService.createDueTasks` already handles as "no tasks exist -- create
 * the first one", so each plant simply starts its cycle at import time.
 */

/**
 * Bumped whenever a change would make an older server misread a newer file.
 * Import refuses anything it does not recognise rather than guessing, because a
 * half-understood bundle writes plants that silently lost their schedules.
 */
export const BUNDLE_FORMAT_VERSION = 1;

export const MANIFEST_ENTRY = 'manifest.json';
export const DATA_ENTRY = 'data.json';

/**
 * Image entries are matched against this rather than having their names joined
 * onto a path. Entry names inside a zip are attacker-controlled and may contain
 * `..`, absolute paths, or NUL bytes; an allowlist of "images/<uuid>.webp"
 * closes zip-slip by construction, without a sanitising step that has to be got
 * right. The id is only ever used to look the entry up in a Map -- the path
 * written to disk is generated by the server (see ImportService).
 */
const IMAGE_ENTRY_PATTERN =
  /^images\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\.webp$/;

export function imageEntryName(imageId: string): string {
  return `images/${imageId}.webp`;
}

/** The image id an entry carries, or null if this is not a valid image entry. */
export function parseImageEntry(entryName: string): string | null {
  return IMAGE_ENTRY_PATTERN.exec(entryName)?.[1] ?? null;
}

// ── The format ───────────────────────────────────────────────────────

export interface BundleManifest {
  app: 'zaindari';
  formatVersion: number;
  exportedAt: string;
  user: { username: string; displayName: string };
  counts: { plants: number; images: number };
  /**
   * Photos whose database row survived but whose file did not. Recorded rather
   * than thrown so that one lost file cannot make a whole garden unexportable.
   */
  missingImages: string[];
}

export interface BundleUser {
  locale: string;
  notificationHour: number;
  notificationMinute: number;
  notificationTimes: Array<{
    taskType: TaskType;
    hour: number;
    minute: number;
  }>;
}

export interface BundleSchedule {
  taskType: TaskType;
  intervalDays: number;
  hour: number | null;
  minute: number | null;
  enabled: boolean;
}

export interface BundleImage {
  /** Join key for `images/<id>.webp`, not restored as a database id. */
  id: string;
  isCurrent: boolean;
  createdAt: string;
}

export interface BundlePlant {
  name: string;
  location: string | null;
  instructions: string | null;
  createdAt: string;
  schedules: BundleSchedule[];
  images: BundleImage[];
}

export interface BundleData {
  user: BundleUser;
  plants: BundlePlant[];
}

// ── Parsing ──────────────────────────────────────────────────────────

function invalid(detail: string): never {
  throw new BadRequestException(
    apiError(ERROR_CODES.bundleInvalid, `Invalid backup file: ${detail}`),
  );
}

const TASK_TYPES = new Set<string>(Object.values(TaskType));

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * A trimmed string of bounded length, or null. Length caps matter here in a way
 * they do not for a DTO: nothing upstream has bounded these, so an 80 MB
 * "location" would otherwise go straight into Postgres.
 */
function optionalText(value: unknown, max: number): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed ? trimmed.slice(0, max) : null;
}

function integerIn(value: unknown, min: number, max: number): number | null {
  if (typeof value !== 'number' || !Number.isInteger(value)) return null;
  return value >= min && value <= max ? value : null;
}

/** Round-trips through Date so an unparseable timestamp cannot reach Prisma. */
function timestamp(value: unknown): Date | null {
  if (typeof value !== 'string') return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

export function parseManifest(raw: unknown): BundleManifest {
  if (!isRecord(raw)) invalid('manifest.json is not an object');

  if (raw.app !== 'zaindari') {
    invalid('this is not a Zaindari backup');
  }

  const version = integerIn(raw.formatVersion, 1, Number.MAX_SAFE_INTEGER);
  if (version === null) invalid('manifest.json has no format version');

  // Refuse rather than guess: a newer file may carry fields whose absence this
  // server would read as "the user turned it off".
  if (version > BUNDLE_FORMAT_VERSION) {
    throw new BadRequestException(
      apiError(
        ERROR_CODES.bundleVersionUnsupported,
        `Backup format version ${version} is newer than this server understands (${BUNDLE_FORMAT_VERSION})`,
        { version, supported: BUNDLE_FORMAT_VERSION },
      ),
    );
  }

  const user = isRecord(raw.user) ? raw.user : {};
  const counts = isRecord(raw.counts) ? raw.counts : {};

  return {
    app: 'zaindari',
    formatVersion: version,
    exportedAt: timestamp(raw.exportedAt)?.toISOString() ?? '',
    user: {
      username: optionalText(user.username, 100) ?? '',
      displayName: optionalText(user.displayName, 100) ?? '',
    },
    counts: {
      plants: integerIn(counts.plants, 0, Number.MAX_SAFE_INTEGER) ?? 0,
      images: integerIn(counts.images, 0, Number.MAX_SAFE_INTEGER) ?? 0,
    },
    missingImages: Array.isArray(raw.missingImages)
      ? raw.missingImages.filter((v): v is string => typeof v === 'string')
      : [],
  };
}

/**
 * Schedules are dropped rather than defaulted when malformed. A plant with no
 * override row falls back through `SchedulesService.getMergedSchedules` to the
 * instance default, which is a defined state; a plant with an invented interval
 * is silent data corruption.
 */
function parseSchedules(raw: unknown): BundleSchedule[] {
  if (!Array.isArray(raw)) return [];

  const seen = new Set<string>();
  const schedules: BundleSchedule[] = [];

  for (const entry of raw) {
    if (!isRecord(entry)) continue;
    if (typeof entry.taskType !== 'string' || !TASK_TYPES.has(entry.taskType)) {
      continue;
    }
    // @@unique([plantId, taskType]) -- a duplicate would fail the insert and
    // take the whole import down with it.
    if (seen.has(entry.taskType)) continue;

    const intervalDays = integerIn(entry.intervalDays, 1, 3650);
    if (intervalDays === null) continue;

    // Hour and minute are one setting: a row with an hour but no minute
    // resolves ambiguously, so they are kept or dropped together.
    const hour = integerIn(entry.hour, 0, 23);
    const minute = hour === null ? null : (integerIn(entry.minute, 0, 59) ?? 0);

    seen.add(entry.taskType);
    schedules.push({
      taskType: entry.taskType as TaskType,
      intervalDays,
      hour,
      minute,
      enabled: entry.enabled !== false,
    });
  }

  return schedules;
}

function parseImages(raw: unknown): BundleImage[] {
  if (!Array.isArray(raw)) return [];

  const images: BundleImage[] = [];
  let currentSeen = false;

  for (const entry of raw) {
    if (!isRecord(entry)) continue;
    if (typeof entry.id !== 'string') continue;
    // Validated against the same allowlist the zip entries are, so a
    // data.json id can never name an entry the extractor would refuse.
    if (parseImageEntry(imageEntryName(entry.id)) === null) continue;

    const createdAt = timestamp(entry.createdAt);
    // At most one current photo per plant: the client reads `currentImage` from
    // a one-element array, so a second would make which photo shows arbitrary.
    const isCurrent = entry.isCurrent === true && !currentSeen;
    if (isCurrent) currentSeen = true;

    images.push({
      id: entry.id,
      isCurrent,
      createdAt: (createdAt ?? new Date()).toISOString(),
    });
  }

  return images;
}

function parsePlants(raw: unknown): BundlePlant[] {
  if (!Array.isArray(raw)) invalid('data.json has no plants array');

  const plants: BundlePlant[] = [];

  for (const entry of raw) {
    if (!isRecord(entry)) continue;

    // The one genuinely required field: a plant with no name is unusable in
    // every view that lists it.
    const name = optionalText(entry.name, 200);
    if (!name) continue;

    plants.push({
      name,
      location: optionalText(entry.location, 200),
      instructions: optionalText(entry.instructions, 5000),
      createdAt: (timestamp(entry.createdAt) ?? new Date()).toISOString(),
      schedules: parseSchedules(entry.schedules),
      images: parseImages(entry.images),
    });
  }

  return plants;
}

function parseUser(raw: unknown): BundleUser {
  const user = isRecord(raw) ? raw : {};

  const times: BundleUser['notificationTimes'] = [];
  const seen = new Set<string>();

  if (Array.isArray(user.notificationTimes)) {
    for (const entry of user.notificationTimes) {
      if (!isRecord(entry)) continue;
      if (
        typeof entry.taskType !== 'string' ||
        !TASK_TYPES.has(entry.taskType)
      ) {
        continue;
      }
      if (seen.has(entry.taskType)) continue;

      const hour = integerIn(entry.hour, 0, 23);
      if (hour === null) continue;

      seen.add(entry.taskType);
      times.push({
        taskType: entry.taskType as TaskType,
        hour,
        minute: integerIn(entry.minute, 0, 59) ?? 0,
      });
    }
  }

  return {
    // Left as a raw string on purpose: `UsersService.update` validates it
    // against SUPPORTED_LOCALES, and that is the check that should stay
    // authoritative. ImportService skips the locale rather than failing if the
    // bundle names one this build does not ship.
    locale: typeof user.locale === 'string' ? user.locale : '',
    notificationHour: integerIn(user.notificationHour, 0, 23) ?? 9,
    notificationMinute: integerIn(user.notificationMinute, 0, 59) ?? 0,
    notificationTimes: times,
  };
}

export function parseBundleData(raw: unknown): BundleData {
  if (!isRecord(raw)) invalid('data.json is not an object');

  return {
    user: parseUser(raw.user),
    plants: parsePlants(raw.plants),
  };
}

/** Parses JSON that came out of a zip, as a typed rejection rather than a 500. */
export function parseJsonEntry(entryName: string, contents: Buffer): unknown {
  try {
    return JSON.parse(contents.toString('utf8'));
  } catch {
    invalid(`${entryName} is not valid JSON`);
  }
}
